name: Lint

on:
  - pull_request
  - push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4

      - name: Setup
        uses: actions/setup-go@v4
        with:
          go-version: "1.22"

      - name: Lint
        run: make lint
